//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hovis.Web.Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_HovisVPD_Details
    {
        public t_HovisVPD_Details()
        {
            this.t_HovisVPD_Documents = new HashSet<t_HovisVPD_Documents>();
        }
    
        public long VPDRefNo { get; set; }
        public Nullable<System.DateTime> DateFirstRaised { get; set; }
        public string RaisedBy { get; set; }
        public string BakeryPONumber { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public string DescriptionOfIssue { get; set; }
        public int IssueCategory { get; set; }
        public string Bakery { get; set; }
        public string SupplierName { get; set; }
        public string SupplierContactDetails { get; set; }
        public string SupplierContactName { get; set; }
        public int Priority { get; set; }
        public string ActionsRequired { get; set; }
        public string OthersInvolved { get; set; }
        public string LastUpdates { get; set; }
        public string CloseOutComments { get; set; }
        public Nullable<System.DateTime> IssueClosureDate { get; set; }
        public string Status { get; set; }
        public int SupplierEngagement { get; set; }
        public string DeliveryLotNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string SupplierReferenceNo { get; set; }
    
        public virtual t_HovisVPD_Category_Drop_Down t_HovisVPD_Category_Drop_Down { get; set; }
        public virtual v_HovisVPD_MasterData_Plants v_HovisVPD_MasterData_Plants { get; set; }
        public virtual t_HovisVPD_Priority_Drop_Down t_HovisVPD_Priority_Drop_Down { get; set; }
        public virtual t_HovisVPD_Supplier_Rating_Drop_Down t_HovisVPD_Supplier_Rating_Drop_Down { get; set; }
        public virtual ICollection<t_HovisVPD_Documents> t_HovisVPD_Documents { get; set; }
    }
}
