//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hovis.Web.Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_HovisVPD_Category_Drop_Down
    {
        public t_HovisVPD_Category_Drop_Down()
        {
            this.t_HovisVPD_Details = new HashSet<t_HovisVPD_Details>();
        }
    
        public int CatID { get; set; }
        public string CatDescription { get; set; }
    
        public virtual ICollection<t_HovisVPD_Details> t_HovisVPD_Details { get; set; }
    }
}
