//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hovis.Web.Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_HovisVPD_Document_Types_Drop_Down
    {
        public t_HovisVPD_Document_Types_Drop_Down()
        {
            this.t_HovisVPD_Documents = new HashSet<t_HovisVPD_Documents>();
        }
    
        public int TypeID { get; set; }
        public string TypeDescription { get; set; }
    
        public virtual ICollection<t_HovisVPD_Documents> t_HovisVPD_Documents { get; set; }
    }
}
