//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hovis.Web.Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_HovisVPD_Transaction_Log
    {
        public long RecID { get; set; }
        public Nullable<long> VPDRefNo { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string SignedInName { get; set; }
        public string UpdateDescription { get; set; }
    }
}
