//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hovis.Web.Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_HovisVPD_Conformance_Stats_Detail
    {
        public long VPDRefNo { get; set; }
        public Nullable<int> WeekRaised { get; set; }
        public Nullable<int> MonthRaised { get; set; }
        public Nullable<int> YearRaised { get; set; }
        public int OpenCritical { get; set; }
        public int AllCritical { get; set; }
        public int OpenMajor { get; set; }
        public int AllMajor { get; set; }
        public int OpenMinor { get; set; }
        public int AllMinor { get; set; }
        public int OpenedLast10Days { get; set; }
        public int ClosedLast10Days { get; set; }
        public int AllOpen { get; set; }
        public int AllClosed { get; set; }
        public int AllLoged { get; set; }
        public string Bakery { get; set; }
        public string SupplierName { get; set; }
        public string ItemCode { get; set; }
    }
}
