//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hovis.Web.Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_HovisVPD_Details
    {
        public long VPDRefNo { get; set; }
        public Nullable<System.DateTime> DateFirstRaised { get; set; }
        public string RaisedBy { get; set; }
        public string BakeryPONumber { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public string DescriptionOfIssue { get; set; }
        public Nullable<int> IssueCategory { get; set; }
        public string IssueCategoryDesc { get; set; }
        public string Bakery { get; set; }
        public string BakeryDesc { get; set; }
        public string SupplierName { get; set; }
        public string SupplierContactDetails { get; set; }
        public string SupplierContactName { get; set; }
        public Nullable<int> Priority { get; set; }
        public string PriorityDescription { get; set; }
        public string ActionsRequired { get; set; }
        public string OthersInvolved { get; set; }
        public string LastUpdates { get; set; }
        public string CloseOutComments { get; set; }
        public Nullable<System.DateTime> IssueClosureDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> SupplierEngagement { get; set; }
        public string SupplierEngagementDesc { get; set; }
        public string DeliveryLotNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string SupplierReferenceNo { get; set; }
    }
}
